### ISSUE TITLE
Modify message

### ISSUE THREAD

**Issue by iGabyTM** [Aust1n46/VentureChat#37]
Since the VentureChatEvent doesn't have any setters, how can I modify the message? I need to replace some characters, and since you cancel AsyncPlayerChatEvent I can't do it there either.

**Comment by Aust1n46** [comment]
AsyncPlayerChatEvent is cancelled at priority Highest, which fires last.  You can modify the event before it reaches VentureChat by listening on a lower priority.

VentureChatEvent is read only and fires after I've already processed the chat.  Modifying the event would invoke modifying the json as well, which is why it's read only.  There theoretically could be an event between AsyncPlayerChatEvent and VentureChat event that fires after VentureChat has decided to process the chat (the player isn't muted, etc) but before processing the json.

**Comment by iGabyTM** [comment]
For some reason my listener with HIGH priority didn't work, thank you for your reply.
